# Generated by Django 2.2.5 on 2019-10-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
